dist: xenial

language: python

python:
  - 3.6
  - nightly

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install vlc mpv libmpv-dev
  - pip install --upgrade pip

install:
  - pip install ".[test]"
  - pip install .

script:
  - coverage run -m pytest tests

after_success:
  - codecov

notifications:
  email: false